### ISSUE TITLE
I'm not sure what the use case would be...

### ISSUE THREAD

**Issue by zetaomegagon** [rhofour/evdi-vnc#1]
How is this different from just using a non-evdi vnc server? How does it work as a "second display"?

**Comment by rhofour** [comment]
So, with a normal VNC server when you connect you end up in a new session just like you'd logged into the computer where the server is running. This is probably what you want if you're looking to login to a server or something similar. 

What evdi-vnc does is it creates a new virtual monitor on the machine that runs the server. As far as that computer is concerned an actual physical monitor just got plugged in, but instead of all of the output going through a cable it's sent through VNC. With evdi-vnc everything is running in the same session which means you could take a window on host machine and drag it over into the virtual EVDI screen (and see it displayed on the VNC client). Note that since evdi-vnc is designed specifically for this use case the vnc server is view-only (you can't click on anything from within the VNC client).

**Does that make sense?**

The main use case I have for something like this is to use a tablet (Android or iOS) as a second screen on a Linux system. There are programs for doing this for both Mac and Windows, but prior to this program there wasn't an easy method on Linux.

I guess I didn't really explain this in the README. I'll put something up there to explain what makes this different from all of the other VNC servers out there.

**Comment by zetaomegagon** [comment]
Awesome, thanks for the explanation. That makes a lot of sense. Definitely
update your readme-- I think this is a valuable project that people should
know about.

What would it take to make the client have write access too? Just curious.

--Elijah Beale

**Comment by rhofour** [comment]
I think the main issue with allowing the client write access is that it wouldn't be very intuitive for users. The client only knows about the area it's displaying, so while the client could control the cursor within that area, the client's cursor would be constrained to just that area. On the other hand, the host computer's cursor can freely move between both screens (since as far as the host system is concerned the new monitor is just like any other monitor).

Do you have a use case where this would be of use?

**Comment by zetaomegagon** [comment]
"Do you have a use case where this would be of use?"

I don't think so. Mainly curious. About how light is evdi-vnc? Depending on
how light it is, there might be a use case on embedded/low power
hardware...?

Just thinking out loud/trying to give a meaningful answer.

--Elijah Beale

Sent from a smallish computer ;)

On Jan 29, 2017 15:06, "Richard A Hofer" <notifications@github.com> wrote:

I think the main issue with allowing the client write access is that it
wouldn't be very intuitive for users. The client only knows about the area
it's displaying, so while the client could control the cursor within that
area, the client's cursor would be constrained to just that area. On the
other hand, the host computer's cursor can freely move between both screens
(since as far as the host system is concerned the new monitor is just like
any other monitor).

Do you have a use case where this would be of use?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rhofour/evdi-vnc/issues/1#issuecomment-275941902>, or mute
the thread

**Comment by rhofour** [comment]
> About how light is evdi-vnc?

evdi-vnc is really simple and minimal, but that's mainly because all the heavy lifting is done in libvncserver and libevdi. I'd guess it could run on an embedded system, but I imagine regular VNC (or even just SSH) would be better there.

**Comment by audunmg** [comment]
I think it's great to use a secondary device such as a tablet or laptop as if it was a secondary screen, with the only requirement being a vncviewer on the secondary device.

I've used a laptop as a secondary screen for a while now, and it works well, but with some minor lag and stutter. I think it has good potential.
